name: Build Mastodon Postbot Image
on:
  push:
    branches:
      - "main"
    paths:
      - "mastodon_postbot.py"
      - "Dockerfile"
      - "requirements.txt"
  schedule:
    - cron: "0 0 * * SUN"
  workflow_dispatch:

jobs:
  build-mastodon-postbot-image:
    runs-on: self-hosted

    env:
      DOCKERHUB_REPO: bonztm/mastodon-postbot

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date --rfc-3339=date)"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: bonztm
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create docker context
        run: |
          docker context create mastodon-postbot

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          endpoint: mastodon-postbot

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.DOCKERHUB_REPO }}:latest,${{ env.DOCKERHUB_REPO }}:${{ steps.date.outputs.date }}

      - name: Remove docker context
        if: always()
        run: docker context rm mastodon-postbot

      - name: Update Dockerhub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: bonztm
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.DOCKERHUB_REPO }}
          readme-filepath: README.md
          short-description: ${{ github.event.repository.description }}
